const slides = [
  {
    title: "Data Portfolio",
    summary:
      "This portfolio highlights internal tools and data products I’ve designed for nonprofit and humanitarian organizations.\n\nMy work focuses on translating complex, ambiguous operational needs into usable systems that support judgment, accountability, and adoption by non-technical users.",
    screen: "./assets/screens/page-01.jpg",
    thumb: "./assets/thumbs/page-01.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
    disableInfo: true,
    overlayHtml:
      '<div class="cover-block"><div class="cover-title">Sunyoung Lie</div><div class="cover-copy">Data portfolio: products that advance nonprofit strategic goals through data collection, analysis, visualization,<br />and knowledge management</div></div>',
  },
  {
    title: "Placements vs. Actively Homeless Animation",
    summary: "Users often assume that the difference in a reduced Actively Homeless number equals the number of Housing Placements. The reality is there are actually many more Housing Placements occurring for each single point reduction in Actively Homeless.\n\nThis animation (shown with sample data) was created to accompany an article describing how much Placements work goes on behind the scenes of reducing Actively Homeless numbers.",
    screen: "./assets/animated/placement-ah.gif",
    thumb: "./assets/thumbs/page-02.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Americares Bulk Activity Data Entry",
    summary: "I created an app for entering quantitative data for an Activity in order to aggregate impact across our Programs. Some Program managers requested the ability to bulk upload spreadsheets, but conforming spreadsheet data to our location requirements would be difficult.\n\nThe solution was an app that had built in mapping so Program managers could insert latitude and longitude in each row through a Google maps interface. I also gave them the ability to group Activities with the same location.",
    screen: "./assets/screens/page-03.jpg",
    thumb: "./assets/thumbs/page-03.jpg",
    mediaScale: 1.08,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Americares Deduplication Worksheet",
    summary: "I was tasked with creating a system to estimate participants that benefited from multiple Americares Activities, without having identifying information about each participant. I created an app that shows our Evaluation Director groups of Activities that are within a reasonable travel distance from each other and serve the same demographic.\n\nThe Director can use their qualitative knowledge to add or subtract to that group, and estimate a low, medium, or high probability of duplicate participants.\n\nI added a population density factor that reduces the probability of duplicate participants if the area is densely populated.",
    screen: "./assets/screens/page-04.jpg",
    thumb: "./assets/thumbs/page-04.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Community Placements One-Page Infographic",
    summary: "Our independently operating Communities often find that their external partners focus on rising numbers of homelessness, which creates a sense of hopelessness around the issue. We wanted communities (regardless of staff capacity) to have a simple way of communicating the work they are doing around housing placements.\n\nThis template (shown with sample data) can be updated by any Community through manual data entry into a Google or excel sheet, creating a simple PDF that can be sent to external partners in media and government, transforming the conversation to a person-centered approach around the individuals actually receiving assistance.",
    screen: "./assets/screens/page-05.jpg",
    thumb: "./assets/thumbs/page-05.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "North Star Dashboard",
    summary: "Community Solutions tracks progress towards several goals over the course of its strategic plan. Many of these goals are qualitative, creating challenges for leadership in assessing the organization’s progress across departments.\n\nThis dashboard displays both quantitative and qualitative goals in an interface that distills progress into three simple chart types, and employs a numerical phase approach in order to enable visual assessment of qualitative goals.",
    screen: "./assets/screens/page-06.jpg",
    thumb: "./assets/thumbs/page-06.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Salesforce Dashboard for All Interventions",
    summary: "I’ve worked in four Salesforce instances in my data analytics career, during which time I’ve enjoyed taking advantage of customizations and formulas in order to provide intuitive data entry and visualization experiences for my staff.\n\nThis dashboard combines several separate programs or Interventions so impact can be compared across the entire work of the organization, for a leadership perspective. The focus is on two separate measures: number of Events per Intervention, and Data Reporting performance for each Intervention.",
    screen: "./assets/screens/page-07.jpg",
    thumb: "./assets/thumbs/page-07.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Built for Zero Wiki",
    summary: "This product was developed to house several years worth of iterations on trainings, definitions, tools, and data collection spreadsheets.\n\nProject management, cross-team collaboration, user experience, technology limitations, and clear branding principles were all important aspects of this product development.\n\nImprovement occurs monthly through feedback gathered in weekly office hours and feedback forms available within the site.",
    screen: "./assets/screens/page-08.jpg",
    thumb: "./assets/thumbs/page-08.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Community Small Multiples",
    summary: "These charts are the first attempt to visualize our data across our independently operating Communities, instead of within a single Community.\n\nThis live Tableau dashboard (shown with sample data) utilizes a moving average and the color range within area maps to display several data points at once, as well as the difference between those data points. Previous versions required users to view these data points as separate elements and extrapolate these differences on their own.",
    screen: "./assets/screens/page-09.jpg",
    thumb: "./assets/thumbs/page-09.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "Aggregated Community Data",
    summary: "Our 105 Communities across the country have a monthly practice of submitting key metrics to us, which we store in our data warehouse. The Communities sometimes skip months, or submit the data for a particular month several months later. There are also issues with outliers and volatility.\n\nDue to these factors, we have only analyzed the data on an individual Community level for insight onto that particular Community.\n\nThis project was an attempt to aggregate the data across all Communities to see if we could gain any insight into national trends. By aligning the Community boundaries with County boundaries, weighting the data by the Census population of the Community, and excluding outliers, we were able to aggregate the various data submissions to create a compelling analysis of national homelessness trends.",
    screen: "./assets/screens/page-10.jpg",
    thumb: "./assets/thumbs/page-10.jpg",
    mediaScale: 1,
    mediaShiftX: "0",
    mediaShiftY: "-1.75%",
  },
  {
    title: "",
    summary:
      "Dataforprogress.org landing page.\n\nThe client needed a captivating home page that communicated the extent of corporate involvement in key legislative issues.",
    screen: "./assets/animated/cap-logos-type-locked.gif",
